name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Replace Firebase placeholders
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          sed -i "s/FIREBASE_API_KEY/$FIREBASE_API_KEY/g" public/signup.js
          sed -i "s/FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" public/signup.js
          sed -i "s/FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID/g" public/signup.js
          sed -i "s/FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" public/signup.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" public/signup.js
          sed -i "s/FIREBASE_APP_ID/$FIREBASE_APP_ID/g" public/signup.js

          sed -i "s/FIREBASE_API_KEY/$FIREBASE_API_KEY/g" public/login.js
          sed -i "s/FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" public/login.js
          sed -i "s/FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID/g" public/login.js
          sed -i "s/FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" public/login.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" public/login.js
          sed -i "s/FIREBASE_APP_ID/$FIREBASE_APP_ID/g" public/login.js

          sed -i "s/FIREBASE_API_KEY/$FIREBASE_API_KEY/g" public/play.js
          sed -i "s/FIREBASE_AUTH_DOMAIN/$FIREBASE_AUTH_DOMAIN/g" public/play.js
          sed -i "s/FIREBASE_PROJECT_ID/$FIREBASE_PROJECT_ID/g" public/play.js
          sed -i "s/FIREBASE_STORAGE_BUCKET/$FIREBASE_STORAGE_BUCKET/g" public/play.js
          sed -i "s/FIREBASE_MESSAGING_SENDER_ID/$FIREBASE_MESSAGING_SENDER_ID/g" public/play.js
          sed -i "s/FIREBASE_APP_ID/$FIREBASE_APP_ID/g" public/play.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
